spring:
  application:
    name: hl-ai-code-app
  # DataSource Config
  datasource:
    url: jdbc:mysql://localhost:3306/hl_ai_code_mother
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
    timeout: 2592000
  profiles:
    active: local
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
# 热 key 探测
hotkey:
  enabled: true
  client-enabled: true
  app-name: hl-ai-code-app
  caffeine-size: 5000
  push-period: 500
  etcd-server: http://127.0.0.1:2379
server:
  port: 8125
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi ??
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hl.hlaicodemother.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
# AI 模型配置
langchain4j:
  open-ai:
    chat-model:
      api-key:
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      response-format: json-object
      strict-json-schema: true
      max-retries: 1
    streaming-chat-model:
      api-key:
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      max-retries: 1
    # 推理 AI 模型配置（用于复杂的推理任务）
    reasoning-streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-reasoner
      max-tokens: 32768
      temperature: 0.1
      log-requests: true
      log-responses: true
    # 智能路由 AI 模型配置（用于简单的分类任务）
    routing-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: <Your API Key>
      model-name: qwen-turbo
      log-requests: true
      log-responses: true
# Dubbo
dubbo:
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 50053
  consumer:
    timeout: 120000
  provider:
    timeout: 120000
